# Generated by Django 5.2.1 on 2025-06-05 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='nb_exemplaires',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
