# Generated by Django 5.2.1 on 2025-06-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_livre_nb_exemplaires_alter_emprunt_date_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='rendu',
            field=models.BooleanField(default=False),
        ),
    ]
